
BULK INSERT SETORES
	FROM 'C:\TTI\setores.csv'
	WITH (  FIELDTERMINATOR = ';', 
			ROWTERMINATOR = ';\n',
			FIRSTROW = 2 ,
			CODEPAGE = 'ACP');

BULK INSERT ACOES
	FROM 'C:\TTI\COTAHIST_A2021.csv'
	WITH (  FIELDTERMINATOR = ';', 
			ROWTERMINATOR = '\n',
			FIRSTROW = 2 ,
			CODEPAGE = 'ACP');

