{
 "title": "TesteDB",
 "time": { "from": "2019-01-02T00:00:00.000Z", "to": "2021-05-18T00:00:00.000Z" },
 "panels": [
  {
   "title": "Volume 2019 por Setor",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nselect set1.SETOR, (SELECT SUM(VOLTOT) from ACOES\r\n\t\t\t\tINNER join SETORES set2 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set2.CODIGO\r\n\t\t\t\tWHERE set2.SETOR = set1.SETOR and YEAR(DATA)=2019\r\n\t\t\t\t) as 'Valor',\r\n\t\t\t\tGETDATE() as time from SETORES set1\r\n\t\t\t\tGROUP BY SETOR\r\n\t\t\t\tORDER BY 'Valor' DESC"
    }
   ]
  },
  {
   "title": "Volume 2020 por Setor",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nselect set1.SETOR, (SELECT SUM(VOLTOT) from ACOES\r\n\t\t\t\tINNER join SETORES set2 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set2.CODIGO\r\n\t\t\t\tWHERE set2.SETOR = set1.SETOR and YEAR(DATA)=2020\r\n\t\t\t\t) as 'Valor',\r\n\t\t\t\tGETDATE() as time from SETORES set1\r\n\t\t\t\tGROUP BY SETOR\r\n\t\t\t\tORDER BY 'Valor' DESC"
    }
   ]
  },
  {
   "title": "Valorização 2019~2020 - por Setor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select GETDATE() as time, SETOR, ((SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set2 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set2.CODIGO\r\n\t\t\t\tWHERE set2.SETOR = set1.SETOR and YEAR(DATA)=2020\r\n\t\t\t\t)-\r\n\t\t\t\t(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set3 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set3.CODIGO\r\n\t\t\t\tWHERE set3.SETOR = set1.SETOR and YEAR(DATA)=2019\r\n\t\t\t\t))/(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set4 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set4.CODIGO\r\n\t\t\t\tWHERE set4.SETOR = set1.SETOR and YEAR(DATA)=2019\r\n\t\t\t\t) as 'Valorização'from SETORES set1\r\n\t\t\t\tGROUP BY SETOR\r\n\t\t\t\tORDER BY 'Valorização'"
    }
   ]
  },
  {
   "title": "Valorização 2019~2020 - por Sub-Setor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*Valorização por subsetor*/\r\nselect GETDATE() as time, SUBSETOR, ((SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set2 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set2.CODIGO\r\n\t\t\t\tWHERE set2.SUBSETOR = set1.SUBSETOR and set2.SETOR = set1.SETOR and YEAR(DATA)=2020\r\n\t\t\t\t)-\r\n\t\t\t\t(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set3 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set3.CODIGO\r\n\t\t\t\tWHERE set3.SUBSETOR = set1.SUBSETOR and set3.SETOR = set1.SETOR and YEAR(DATA)=2019\r\n\t\t\t\t))/(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set4 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set4.CODIGO\r\n\t\t\t\tWHERE set4.SUBSETOR = set1.SUBSETOR and set4.SETOR = set1.SETOR and YEAR(DATA)=2019\r\n\t\t\t\t) as 'Valorização'from SETORES set1\r\n\t\t\t\tGROUP BY SETOR, SUBSETOR\r\n\t\t\t\tORDER BY 'Valorização'"
    }
   ]
  },
  {
   "title": "Valorização 2019~2020 - por Segmento",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select GETDATE() as time, SEGMENTO, ((SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set2 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set2.CODIGO\r\n\t\t\t\tWHERE set2.SUBSETOR = set1.SUBSETOR and set2.SETOR = set1.SETOR and set2.SEGMENTO = set1.SEGMENTO and YEAR(DATA)=2020\r\n\t\t\t\t)-\r\n\t\t\t\t(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set3 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set3.CODIGO\r\n\t\t\t\tWHERE set3.SUBSETOR = set1.SUBSETOR and set3.SETOR = set1.SETOR and set3.SEGMENTO = set1.SEGMENTO and YEAR(DATA)=2019\r\n\t\t\t\t))/(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES\r\n\t\t\t\tINNER join SETORES set4 on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = set4.CODIGO\r\n\t\t\t\tWHERE set4.SUBSETOR = set1.SUBSETOR and set4.SETOR = set1.SETOR and set4.SEGMENTO = set1.SEGMENTO and YEAR(DATA)=2019\r\n\t\t\t\t) as 'Valorização'from SETORES set1\r\n\t\t\t\tGROUP BY SETOR, SUBSETOR, SEGMENTO\r\n\t\t\t\tORDER BY 'Valorização'"
    }
   ]
  },
  {
   "title": "Maiores Ações por Setor, Sub-setor e Segmento",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "select SETOR, SUBSETOR, SEGMENTO, CODNEG, NOMRES, SUM(VOLTOT) as VOLUME, \r\n\t\t(SELECT SUM(PREMED)/COUNT(PREMED) from ACOES ac2\r\n\t\t where YEAR(DATA)=2019 and ac2.CODNEG = ac1.CODNEG) as 'Preço Medio 2019',\r\n\t\t (SELECT SUM(PREMED)/COUNT(PREMED) from ACOES ac3\r\n\t\t where YEAR(DATA)=2020 and ac3.CODNEG = ac1.CODNEG) as 'Preço Medio 2020',\r\n\t\t (SELECT SUM(PREMED)/COUNT(PREMED) from ACOES ac4\r\n\t\t where YEAR(DATA)=2020 and ac4.CODNEG = ac1.CODNEG) as 'Preço Medio 2021'from ACOES ac1\r\nINNER join SETORES on REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE (CODNEG, '0', ''),'1', ''),'2', ''),'3', ''),'4', ''),'5', ''),'6', ''),'7', ''),'8', ''),'9', '') = CODIGO\r\ngroup by SETOR, SUBSETOR, SEGMENTO, CODNEG, NOMRES\r\norder by SETOR, SUM(VOLTOT) desc"
    }
   ]
  },
  {
   "title": "Volume Total por Ação",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\tTOP 10 GETDATE() as time,\n\t\t\t\t\tCODNEG,\n\t\t\t\t\tSUM(VOLTOT) as VOLUME from ACOES\n\t\t\tgroup by CODNEG\n\t\t\tORDER by SUM(VOLTOT) DESC"
    }
   ]
  },
  {
   "title": "Cotação por dia das 30 maiores ações",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select DATA as time, CODNEG, PREMED from ACOES\r\n\t\t\t\twhere CODNEG IN (select TOP 30 codneg as total from ACOES group by CODNEG order by SUM(VOLTOT) DESC)"
    }
   ]
  },
  {
   "title": "Valorização 2019~2020 - 30 maiores ações",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select GETDATE() as time, CODNEG, ((select SUM(PREMED)/COUNT(PREMED) from ACOES ac2\r\n\t\t\t\t\t\t\t\twhere ac2.CODNEG = ac1.CODNEG and YEAR(DATA)=2020)-\r\n\t\t\t\t\t\t\t\t(select SUM(PREMED)/COUNT(PREMED) from ACOES ac2\r\n\t\t\t\t\t\t\t\twhere ac2.CODNEG = ac1.CODNEG and YEAR(DATA)=2019))/\r\n\t\t\t\t\t\t\t\t(select SUM(PREMED)/COUNT(PREMED) from ACOES ac2\r\n\t\t\t\t\t\t\t\twhere ac2.CODNEG = ac1.CODNEG and YEAR(DATA)=2019) as 'Valorização' from ACOES ac1\r\n\t\t\t\twhere CODNEG IN (select TOP 30 codneg as total from ACOES where CODNEG != 'IBOV11' group by CODNEG order by SUM(VOLTOT) DESC)\r\n\t\t\t\tGROUP BY CODNEG\r\n\t\t\t\tORDER BY 'Valorização'"
    }
   ]
  }
 ]
}